apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-pipeline-environment.serviceAccountName" . }}
  labels:
    {{- include "azure-pipeline-environment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}