apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "schedule-pod-restart.name" . }}
  labels:
    {{- include "schedule-pod-restart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "schedule-pod-restart.serviceAccountName" . }}
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:{{ include "schedule-pod-restart.imageTag" . }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - kubectl delete pods -l {{ .Values.cronjob.podLabels }} --namespace={{ .Release.Namespace }}
          restartPolicy: OnFailure
