apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "schedule-pod-restart.role" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "list"
  - "delete"
  - "get"
